[environment]
; number of qubits
n_qubits = 3
; number of additional ancilla, measured in 0. Ancilla can be initialized to 0, + or T
n_ancilla = 1
ancilla_init = T
; gate set
gateset = CX, H, T, Tdg
; maximum circuit depth the agent can build
max_depth = 40
; min and max circuit depth for the target
min_target_depth = 5
max_target_depth = 40
; circuit depth sampled using either uniform (default) or gaussian distribution
use_normal = True
mean_target_depth = 5
std_depth = 5
; target_fidelity is there to accept some numerical error, default is 0.999 or 1e-3 error
target_fidelity = 0.99
depth_penalty = False
gate_penalty = []

; Connectivity/Architecture
; for each qubit i [connectivity.i]:
; 	control : specifiy which other qubit it can control 
; 		e.g. connectivity.0 control = 1 allows for a CNOT between 0 and 1 with control on 0
; 	target : what gates can be performed on qubit i, single qubit and target of control gates
[connectivity.0]
control = 3
target = CX, CCX

[connectivity.1]
control = 3
target = CX

[connectivity.2]
control = 3, 0
target = CX

[connectivity.3]
control = 0, 1, 2
target = CCX, CX, H, T, Tdg
